blog-do-willian/Models/BlogContext.cs
using System;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace blog_do_willian.Models
{
    public class BlogContext : DbContext
    {
        public DbSet<Post> Posts { get; set; }

        public BlogContext() : base ("DefaultConnection")
        {

        }
    }
}

blog-do-willian/Models/Post.cs
using System;
using System.Data.Entity;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace blog_do_willian.Models
{
    public class Post
    {
        public int Id { get; set; }
        
        [Required]
        [StringLength(500)]
        public string Title { get; set; }

        public DateTime DataAdded { get; set; }

        public DateTime? DataUpdate { get; set; }

        [Required]
        [StringLength(3000)]
        public string PostingBody { get; set; }

    }
}

blog-do-willian/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace blog_do_willian.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

blog-do-willian/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using blog_do_willian.Models;

namespace blog_do_willian.Controllers
{
    public class PostsController : Controller

    {
        private BlogContext _context = new BlogContext();
        // GET: Posts
        public ActionResult Index()
        {
            var posts =_context.Posts.ToList();
            return View(posts);
        }

        public ActionResult Details(int id)
        {
            var post = _context.Posts.SingleOrDefault(p => p.Id == id);
            if(post == null)
            {
                return HttpNotFound(); 
            }


                return View();
        }

        public ActionResult Edit(int id)
        {
            return View();
        }
        public ActionResult Delete(int id)
        {
            return View();
        }
        public ActionResult DeleteComplete(int id)
        {
            return View();
        }
        [HttpPost]
        public ActionResult Save(Post post)
        {
            return View();
        }


    }
}

blog-do-willian/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

blog-do-willian/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

blog-do-willian/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

blog-do-willian/Views/Posts/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

blog-do-willian/Views/Posts/Details.cshtml
@model blog_do_willian.Models.Post
@{
    ViewBag.Title = "Details";
}

<h2>Detalhes</h2>

<div class="form-group">
    @Html.LabelFor(p => p.Title)
    <div>@Model.Title</div>
</div>
<div class="form-group">
    @Html.LabelFor(p => p.DataAdded) | @Html.LabelFor(p => p.DataUpdate)
    <div>@Model.DataAdded | @Model.DataUpdate</div>
</div>
<div>
    @Html.LabelFor(p => p.PostingBody)
    <div>@Model.PostingBody</div>
</div>

blog-do-willian/Views/Posts/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

blog-do-willian/Views/Posts/Index.cshtml
@model IEnumerable <blog_do_willian.Models.Post>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

@Html.ActionLink("Novo Post", "New", "Posts", null, new { @class = "btn btn-primary" })

<br />
<br />




<table id="posts" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Título</th>
            <th>Data do Post</th>
            <th>Post</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var post in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(post.Title, "Details","Posts", new { id = post.Id}, null)
                </td>

                <td>
                    @post.DataAdded
                </td> 

                <td>
                    @post.PostingBody
                </td>
                
            </tr>

        }
    </tbody>
</table>

blog-do-willian/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nome do aplicativo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>